// TODO - Implement lexical error result type
#[derive(Debug, PartialEq, Clone)]
pub enum Token {
    // Keywords
    And,
    Do,
    Then,
    If,
    Else,
    ElseIf,
    End,
    False,
    True,
    For,
    In,
    Function,
    Mut,
    Nil,
    Not,
    Or,
    While,
    Repeat,
    Return,
    Until,
    Require,
    Break,

    // Operations
    //   +     -   *    /    %    ^    #
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    Pow,
    Len,

    //    &       ~       |       <<      >>     //
    BitAnd,
    BitOr,
    BitNot,
    ShiftL,
    ShiftR,
    Idiv,

    //   ==       ~=     <=      >=      <       >     =
    Equal,
    NotEq,
    LesEq,
    GreEq,
    Less,
    Greater,
    Assign,

    //  (       )       {      }      [       ]      ::
    ParL,
    ParR,
    CurlyL,
    CurlyR,
    SqurL,
    SqurR,
    DoubColon,

    //      ;        :       ,      .    <>     ..
    SemiColon,
    Colon,
    Comma,
    Dot,
    Concat,
    Dots,
    Arrow,

    // Data types, (refers to to their actual value no keywords)
    Int { value: i32 },
    Float { value: f32 },
    String { value: String },
    Bool { value: bool },
    Byte { value: u8 },

    Identifier(String),
    Numbers,

    // End of line
    EoS,
}

#[cfg(test)]
pub const TOKENS_MOCK: [&Token; 54] = [
    // Testing operator and comments
    &Token::Sub,
    &Token::Add,
    &Token::Mul,
    &Token::Mod,
    &Token::Pow,
    &Token::Len,
    &Token::BitAnd,
    &Token::BitOr,
    &Token::ParL,
    &Token::ParR,
    &Token::CurlyL,
    &Token::CurlyR,
    &Token::SqurL,
    &Token::SqurR,
    &Token::SemiColon,
    &Token::Comma,
    &Token::Colon,
    &Token::Colon,
    &Token::Div,
    &Token::Div,
    &Token::Equal,
    &Token::Equal,
    &Token::NotEq,
    &Token::NotEq,
    &Token::LesEq,
    &Token::ShiftL,
    &Token::Less,
    &Token::Greater,
    &Token::GreEq,
    &Token::ShiftR,
    &Token::ShiftR,
    &Token::Arrow,
    // Testing keywords
    &Token::Mut,
    &Token::Require,
    &Token::And,
    &Token::Break,
    &Token::Do,
    &Token::Else,
    &Token::ElseIf,
    &Token::End,
    &Token::False,
    &Token::For,
    &Token::Function,
    &Token::If,
    &Token::In,
    &Token::Nil,
    &Token::Not,
    &Token::Or,
    &Token::Repeat,
    &Token::Return,
    &Token::Then,
    &Token::True,
    &Token::Until,
    &Token::While,
];
